apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnigcloud-app
  namespace: omnigcloud-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omnigcloud-app
  template:
    metadata:
      labels:
        app: omnigcloud-app
    spec:
      containers:
        - name: omnigcloud-app
          image: image-registry.openshift-image-registry.svc:5000/omnigcloud-prod/omnigcloud-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: omnigcloud-app-svc
  namespace: omnigcloud-prod
spec:
  selector:
    app: omnigcloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: omnigcloud-app-route
  namespace: omnigcloud-prod
spec:
  to:
    kind: Service
    name: omnigcloud-app-svc
  port:
    targetPort: 3000
  tls:
    termination: edge
